import { Rubik } from 'next/font/google';
import { notFound } from 'next/navigation';

import Layout from '@/components/layout/Layout';
import { Toaster } from '@/components/ui/toaster';
import './globals.css';
import { getCurrentUser } from '@/lib/session';

import Providers from './providers';

const rubik = Rubik({ subsets: ['latin'], weight: ['300', '400', '500'], display: 'swap' });

export const metadata = {
  title: 'Recipes App',
  description: 'Generated by create next app'
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const user = await getCurrentUser();

  return (
    <html lang='en'>
      <body className={rubik.className}>
        <Providers>
          <Layout
            user={{
              name: user?.name,
              image: user?.image,
              email: user?.email
            }}
          >
            {' '}
            {children}
          </Layout>
          <Toaster />
        </Providers>
      </body>
    </html>
  );
}
